### ISSUE TITLE
Chinese languag

### ISSUE THREAD

**Issue by soul-of-god** [Mnemotechnician/New-Controls-Public#1]
[bundle_zh_CN.zip](https://github.com/Mnemotechnician/New-Controls-Public/files/8103846/bundle_zh_CN.zip)

**Comment by Mnemotechnician** [comment]
not gonna lie, Chinese communist party was something i expected the least

**Comment by Mnemotechnician** [comment]
it's in the new release now

**Comment by soul-of-god** [comment]
But this MOD is still used by a lot of people in China

**Comment by Mnemotechnician** [comment]
i mean it's most likely not used by anybody at all (according to traffic insights) but I've added your bundle anyways and it's already available in the latest release

**Comment by soul-of-god** [comment]
ok
