### ISSUE TITLE
136?

### ISSUE THREAD

**Issue by 1stvaliduser** [Mnemotechnician/New-Controls-Public#2]
Could you update(revive) it? Please...

**Comment by Mnemotechnician** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
idk, I'll try

**Comment by Mnemotechnician** [comment]
The latest update now supports v136.
Hopefully the autoupdater won't make v135 players (if there are any) autoupdate the mod...
