### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrRoomba** [Mnemotechnician/New-Controls-Public#4]
Once i click the enable button on mobile it crashes

**Comment by Mnemotechnician** [comment]
???
Can you at least provide a crash log; I'm not a magican and i can't guess what the issue is

Go to the settings menu, click "game data", press the "export crash logs" button and send them here

**Comment by MrRoomba** [comment]
I'm on a mobile device

**Comment by Mnemotechnician** [comment]
and
you think it's that easy to hack into a remote mobile device?

(i hope it won't take you 4 days to reply again)

**Comment by Mnemotechnician** [comment]
ok, you're refusing to provide any logs, and i can't reproduce this issue without knowing anything about it.
