### ISSUE TITLE
Tapping anywhere with custom behavior on crashes on mobile

### ISSUE THREAD

**Issue by RGBProductions** [Mnemotechnician/New-Controls-Public#6]
**Steps to Reproduce:**
1. Enter any sector
2. Turn on the custom behavior panel
3. Tap anywhere that isn't part of the panel

**Relevant crash log**
[crash_1681754428534.txt](https://github.com/Mnemotechnician/New-Controls-Public/files/11254076/crash_1681754428534.txt)

**Comment by Mnemotechnician** [comment]
😩

**Comment by Mnemotechnician** [comment]
A recent study shows that the mod is incompatible with v140+ due to the fact that newer versions have the command system removed from the game; will fix it later

**Comment by Mnemotechnician** [comment]
After forgetting to do it for 3 days, I finally made it compatible. You should be able to update now.
